posts: 文章
category: 文章分类
categories: 文章分类
tag: 文章标签
tags: 文章标签
archives: 文章归档
about: 关于
contact: Contact
friends: 友情链接
startRead: 开始阅读
recommendedPosts: 文章推荐
publishDate: 发布日期
updateDate: 修改时间
readCount: 阅读次数
wordCount: 文章字数
readTimes: 阅读时长
Minutes: 分
readMore: 阅读更多
toc: 目录
curr: 正在阅读
prev: 上一篇
next: 下一篇
search: 搜索
searchTip: 请输入搜索的关键字
postTagTitle: 文章标签
postCategoryTitle: 文章分类
categoryRadarTitle: 文章分类雷达图
categoryNumber: Number of Categories
categoryEmptyTip: Your posts has no categories information yet.
postCharts: 文章统计图
postPublishChart: 文章发布统计图
categoriesChart: 文章分类统计图
top10TagsChart: TOP10 标签统计图
postsNumberName: 文章总数
maximum: Maximum
minimum: Minimum
average: Average
myProjects: 我的项目
mySkills: 我的技能
otherSkills: 其他技能
gallery: Gallery
notag: No tag
from: From
reprint: Reprint policy
author: 作者
link: Link
use: All articles in this blog are used except for special statements
licensed: reprint polocy. If reproduced, please indicate source
cc_by_url: https://creativecommons.org/licenses/by/4.0/deed.zh
cc_by_name: CC BY 4.0
cc_by_nd_url: https://creativecommons.org/licenses/by-nd/4.0/deed.zh
cc_by_nd_name: CC BY-ND 4.0
cc_by_sa_url: https://creativecommons.org/licenses/by-sa/4.0/deed.zh
cc_by_sa_name: CC BY-SA 4.0
cc_by_nc_url: https://creativecommons.org/licenses/by-nc/4.0/deed.zh
cc_by_nc_name: CC BY-NC 4.0
cc_by_nc_nd_url: https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh
cc_by_nc_nd_name: CC BY-NC-ND 4.0
cc_by_nc_sa_url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
cc_by_nc_sa_name: CC BY-NC-SA 4.0
cc_0_url: https://creativecommons.org/publicdomain/zero/1.0/
toTheExtentPossibleUnderLaw: To the extent possible under law,
hasWaivedAllCopyrightAndRelatedOrNeighboringRightsTo: has waived all copyright and related or neighboring rights to
workPublishedFrom: ". This work is published from:"
cc_0_country: United States.
cc_0_content: US
noreprint: This article is not allowed to reprint.
paycontact: Please contact the author
payreprint: to pay for reprinting.
pleaseFollowReprintPolicy: Copied successfully, please follow the reprint policy of this article
checkPolicy: more
